/**********************************************************************
 * Extern for hoodie
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var hoodie = {
  "account": {
    "destroy": function () {},
    "get": function () {},
    "hook": {
      "after": function () {},
      "before": function () {},
      "remove": {
        "after": function () {},
        "before": function () {}
      }
    },
    "off": function () {},
    "on": function () {},
    "one": function () {},
    "profile": {
      "get": function () {},
      "update": function () {}
    },
    "request": function () {},
    "signIn": function () {},
    "signOut": function () {},
    "signUp": function () {},
    "update": function () {},
    "validate": function () {}
  },
  "connectionStatus": {
    "check": function () {},
    "isChecking": {},
    "off": function () {},
    "ok": {},
    "on": function () {},
    "ready": {},
    "reset": function () {},
    "startChecking": function () {},
    "stopChecking": function () {}
  },
  "log": {
    "debug": function () {},
    "error": function () {},
    "info": function () {},
    "level": {},
    "prefix": {},
    "scoped": function () {},
    "warn": function () {}
  },
  "off": function () {},
  "on": function () {},
  "one": function () {},
  "plugin": function () {},
  "request": function () {},
  "store": {
    "add": function () {},
    "connect": function () {},
    "db": {
      "__opts": {
        "adapter": {},
        "name": {}
      },
      "_adapter": {},
      "_allDocs": function () {},
      "_bulkDocs": function () {},
      "_changes": function () {},
      "_close": function () {},
      "_compact": function () {},
      "_destroy": function () {},
      "_doCompaction": function () {},
      "_events": {
        "closed": {
          "listener": function () {}
        },
        "destroyed": {
          "listener": function () {}
        }
      },
      "_get": function () {},
      "_getAttachment": function () {},
      "_getLocal": function () {},
      "_getRevisionTree": function () {},
      "_id": function () {},
      "_info": function () {},
      "_maxListeners": {},
      "_meta": {
        "blobSupport": {},
        "instanceId": {},
        "name": {}
      },
      "_putLocal": function () {},
      "_removeLocal": function () {},
      "adapter": {},
      "addListener": function () {},
      "allDocs": function () {},
      "auto_compaction": {},
      "bulkDocs": function () {},
      "bulkGet": function () {},
      "changes": function () {},
      "close": function () {},
      "compact": function () {},
      "compactDocument": function () {},
      "destroy": function () {},
      "doc": function () {},
      "emit": function () {},
      "get": function () {},
      "getAttachment": function () {},
      "hoodieApi": function () {},
      "hoodieSync": function () {},
      "id": function () {},
      "info": function () {},
      "listenerCount": function () {},
      "listeners": function () {},
      "name": {},
      "on": function () {},
      "once": function () {},
      "post": function () {},
      "prefix": {},
      "put": function () {},
      "putAttachment": function () {},
      "query": function () {},
      "registerDependentDatabase": function () {},
      "remove": function () {},
      "removeAllListeners": function () {},
      "removeAttachment": function () {},
      "removeListener": function () {},
      "revsDiff": function () {},
      "setMaxListeners": function () {},
      "sync": function () {},
      "taskqueue": {
        "addTask": function () {},
        "db": {},
        "execute": function () {},
        "fail": function () {},
        "failed": {},
        "isReady": {},
        "queue": {},
        "ready": function () {}
      },
      "type": function () {},
      "viewCleanup": function () {}
    },
    "disconnect": function () {},
    "find": function () {},
    "findAll": function () {},
    "findOrAdd": function () {},
    "isConnected": function () {},
    "isPersistent": function () {},
    "off": function () {},
    "on": function () {},
    "one": function () {},
    "pull": function () {},
    "push": function () {},
    "remove": function () {},
    "removeAll": function () {},
    "reset": function () {},
    "sync": function () {},
    "update": function () {},
    "updateAll": function () {},
    "updateOrAdd": function () {},
    "withIdPrefix": function () {}
  },
  "trigger": function () {},
  "url": {}
};
/**********************************************************************
 * End Generated Extern for hoodie
/**********************************************************************/
